apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-cert2
  namespace: vaultwarden
spec:
  secretName: letsencrypt2
  issuerRef:
    name: letsencrypt 
    kind: ClusterIssuer
  commonName: example@example.com
  dnsNames:
    - example@example.com
