# apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: vaultwarden.mvarela.io
    http:
      paths:
      - path: /
        backend:
          serviceName: vaultwarden-service
          servicePort: 80
  tls:
  - hosts:
    - vaultwarden.mvarela.io
    secretName: vaultwarden-cert
  annotations:
    cert-manager.io/issuer: letsencrypt