---
ports:
  web:
    port: 80
  websecure:
    port: 443

ingressRoute:
  dashboard:
    enabled: false

# Enable HTTPS redirection on web entrypoint
additionalArguments:
  - --entryPoints.web.http.redirections.entryPoint.to: websecure
  - --entryPoints.web.http.redirections.entryPoint.scheme: https

securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0
